### ISSUE TITLE
Bump to 0.2.3 in `solang-parser` was breaking

### ISSUE THREAD

**Issue by smoelius** [hyperledger/solang#1212]
Hi. The bump from version 0.2.2 to 0.2.3 in `solang-parser` was breaking, as it changed the public API. Here is an example:
https://github.com/hyperledger/solang/commit/28da91132fba931acdc8a89aa9d644ea21f4edb4#diff-f405bd2c266e394a31b0a0cae986996dfd75f274cb2c468243e37d47eef640dfL486

Thanks for the useful crate, and sorry for the pedantry.

**Comment by seanyoung** [comment]
> Hi. The bump from version 0.2.2 to 0.2.3 in `solang-parser` was breaking, as it changed the public API. Here is an example: [28da911#diff-f405bd2c266e394a31b0a0cae986996dfd75f274cb2c468243e37d47eef640dfL486](https://github.com/hyperledger/solang/commit/28da91132fba931acdc8a89aa9d644ea21f4edb4#diff-f405bd2c266e394a31b0a0cae986996dfd75f274cb2c468243e37d47eef640dfL486)
> 
> Thanks for the useful crate, and sorry for the pedantry.

Yes, you are right. 
 - Since this crate exposes the parse tree, it is nearly impossible to not have breaking changes when language features are added, like here https://github.com/hyperledger/solang/commit/28da91132fba931acdc8a89aa9d644ea21f4edb4#diff-f405bd2c266e394a31b0a0cae986996dfd75f274cb2c468243e37d47eef640dfR310 for user defined types
 - solang-parser is still 0.* so breaking changes are allowed according to semver

I guess an alternative would be to have new major versions for every release, and end up with some big version nunbers.

**Comment by smoelius** [comment]
> * solang-parser is still 0.* so breaking changes are allowed according to semver

Is that a thing? I'm aware of Cargo's "[left-most non-zero](https://doc.rust-lang.org/cargo/reference/semver.html#change-categories)" convention, but I didn't realize all development releases had such leniency.

Either way, I respect your decision to consider `solang-parser` exempt.

But could I suggest adding something to the README to indicate this? I could propose something in a PR if you like.

**Comment by smoelius** [comment]
I proposed #1213.

> I was thinking of [semver development releases](https://semver.org/#spec-item-4)

Thanks very much for showing me this!
