### ISSUE TITLE
How to originate lamports transfer from the PDA

### ISSUE THREAD

**Issue by kupermind** [hyperledger/solang#1371]
Hi guys,

Please let us know how / if it is possible to originate lamports transfer from the PDA via the means of solang. The idea is to have the escrow account where the program forces to transfer lamports from the singer, such that the return of lamports from that escrow account is possible only via another function defined in the program.

We were able to try the approach with the `createAccountWithSeed()` for these purposes, but the owner of the created escrow can always take out funds at any moment.

We understand that `createAccountWithSeed()` is not related to the PDA, however we could not find information related to something like the `invoke_signed()` function in Rust as defined [here](https://www.soldev.app/course/cpi):
```
invoke_signed(
    &instruction,
    accounts,
    &[&["First addresses seed"],
        &["Second addresses first seed",
        "Second addresses second seed"]],
)?;
```

Thanks a lot for your input!

**Comment by LucasSte** [comment]
Hey @kupermind, `invoke_signed` can be replicated using this tutorial: https://solang.readthedocs.io/en/latest/language/functions.html#passing-seeds-with-external-calls-on-solana

**Comment by LucasSte** [comment]
> The idea is to have the escrow account where the program forces to transfer lamports from the singer, such that the return of lamports from that escrow account is possible only via another function defined in the program.

Does the suggestion I gave you help with this? If not, I can look further into your problem.

This question is very Solana specific maybe it is worth searching how to do it in a non-Solidity environment first and then we can help you translate it to Solidity.

**Comment by LucasSte** [comment]
> Hey @kupermind, `invoke_signed` can be replicated using this tutorial: https://solang.readthedocs.io/en/latest/language/functions.html#passing-seeds-with-external-calls-on-solana

Depending on the instruction you want to invoke, you'll need to manually encode the data and instruction ID. This process is still very manual in Solidity and needs improvements in our side. Please, let us know if you need further help.

**Comment by kupermind** [comment]
Hey @LucasSte,

Thanks a lot for your reply! Somehow we missed that part of the tutorial :). We will try that approach soon.

From the example it was not really clear about the number of seeds. Do I understand correctly that if I have only one account as a signer (which is the PDA), can I pass only one seed, even though I have more than one argument (other arguments will have `is_signer=false`)?

Thanks again!

**Comment by kupermind** [comment]
Hey @LucasSte,

We are trying to follow your advice for the PDA lamports transfer. We were able to set up the PDA account inside of our program and fund it correctly with lamports. The result of that is that before the PDA creation its info is null, and after we are getting the correct output:
```
{
  data: <Buffer >,
  executable: false,
  lamports: 100001000,
  owner: PublicKey [PublicKey(44yaZsbaaMmt1MzVaVQQhbqpxatZZ4h4LX1V6q8MgPKo)] {
    _bn: <BN: 2d97c6e8b8475ed50e54d9ef928ec3eb2d5073988eddf840dedbf57401517a92>
  },
  rentEpoch: 18446744073709552000,
  space: 0
}
```
where `44yaZsbaaMmt1MzVaVQQhbqpxatZZ4h4LX1V6q8MgPKo` is the our programId.

However, when transferring lamports to another account from the PDA, we are getting the following error:
```
Program Error: SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: instruction spent from the balance of an account it does not own
    at Connection.sendEncodedTransaction (/Users/kupermind/dev/autonolas-registries/integrations/solana/node_modules/@solana/web3.js/src/connection.ts:5882:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/Users/kupermind/dev/autonolas-registries/integrations/solana/node_modules/@solana/web3.js/src/connection.ts:5841:20)
    at async sendAndConfirmRawTransaction (/Users/kupermind/dev/autonolas-registries/integrations/solana/node_modules/@project-serum/anchor/src/provider.ts:318:21)
    at async AnchorProvider.sendAndConfirm (/Users/kupermind/dev/autonolas-registries/integrations/solana/node_modules/@project-serum/anchor/src/provider.ts:149:14)
    at async MethodsBuilder.rpc [as _rpcFn] (/Users/kupermind/dev/autonolas-registries/integrations/solana/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:29:16)
    at async Context.<anonymous> (/Users/kupermind/dev/autonolas-registries/integrations/solana/test/ServiceRegistrySolana.js:138:13) {
  logs: [
    'Program 44yaZsbaaMmt1MzVaVQQhbqpxatZZ4h4LX1V6q8MgPKo invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 failed: instruction spent from the balance of an account it does not own',
    'Program 44yaZsbaaMmt1MzVaVQQhbqpxatZZ4h4LX1V6q8MgPKo consumed 2940 of 200000 compute units',
    'Program 44yaZsbaaMmt1MzVaVQQhbqpxatZZ4h4LX1V6q8MgPKo failed: instruction spent from the balance of an account it does not own'
  ],
  programErrorStack: ProgramErrorStack {
    stack: [
      [PublicKey [PublicKey(44yaZsbaaMmt1MzVaVQQhbqpxatZZ4h4LX1V6q8MgPKo)]],
      [PublicKey [PublicKey(11111111111111111111111111111111)]]
    ]
  }
}
Error Message: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: instruction spent from the balance of an account it does not own
```

We have created two functions for `invoke_sign` interaction in the file: [create_account_pda](https://github.com/valory-xyz/autonolas-registries/blob/8fa180fe8f28894dc785bed856374d1a780214ef/integrations/solana/contracts/SystemInstruction.sol#L30-L47) and [transfer_pda](https://github.com/valory-xyz/autonolas-registries/blob/8fa180fe8f28894dc785bed856374d1a780214ef/integrations/solana/contracts/SystemInstruction.sol#L49-L64) that are based on the PDA bump and our hardcoded seed.

The PDA account is created and funded inside the [activateRegistration](https://github.com/valory-xyz/autonolas-registries/blob/8fa180fe8f28894dc785bed856374d1a780214ef/integrations/solana/contracts/ServiceRegistrySolana.sol#L110-L136) function, line [129](https://github.com/valory-xyz/autonolas-registries/blob/8fa180fe8f28894dc785bed856374d1a780214ef/integrations/solana/contracts/ServiceRegistrySolana.sol#L129).

We are trying to execute the transfer back from the PDA account to the original payer in the function [terminate](https://github.com/valory-xyz/autonolas-registries/blob/8fa180fe8f28894dc785bed856374d1a780214ef/integrations/solana/contracts/ServiceRegistrySolana.sol#L138-L179) on line [172](https://github.com/valory-xyz/autonolas-registries/blob/8fa180fe8f28894dc785bed856374d1a780214ef/integrations/solana/contracts/ServiceRegistrySolana.sol#L172).

The test that performs the describe behavior is located [here](https://github.com/valory-xyz/autonolas-registries/blob/8fa180fe8f28894dc785bed856374d1a780214ef/integrations/solana/test/ServiceRegistrySolana.js#L100-L154).

We are trying to understand why we were able to fund the account by the means of the system program, but for the transfer back the instruction requires the ownership of a SystemProgram rather than the PDA, since the seed is passed specifically for the PDA.

Steps to reproduce the error:
```
git clone --recursive git@github.com:valory-xyz/autonolas-registries.git
git checkout pda_transfer
cd integrations/solana
yarn
npm run build
npm run setup
npm run test
```

We would be grateful for any help related to understanding the issue and / or the means of debugging it.

Apologies for the long text, however it was the only way to express the issue details.

Thanks for your help!!

**Comment by LucasSte** [comment]
> From the example it was not really clear about the number of seeds. Do I understand correctly that if I have only one account as a signer (which is the PDA), can I pass only one seed, even though I have more than one argument (other arguments will have `is_signer=false`)?

Yes, I think this will work.

**Comment by LucasSte** [comment]
Both your functions `create_account_pda` and `transfer_pda` are not correctly implemented. You must use the `Instruction.TransferWithSeed` and `Instruction.CreateAccountWithSeed` for your seeds not to be ignored.
Instead of coding your own functions, you may utilize [create_account_with_seed](https://github.com/hyperledger/solang/blob/01707781adbe8531b29dfc5a942292e60b8c79a4/solana-library/system_instruction.sol#L57) and [transfer_with_seed](https://github.com/hyperledger/solang/blob/01707781adbe8531b29dfc5a942292e60b8c79a4/solana-library/system_instruction.sol#L141) directly from the SystemInstruction library we provide.

Here is an example of how to use these functions with your contract: https://github.com/hyperledger/solang/blob/01707781adbe8531b29dfc5a942292e60b8c79a4/integration/solana/system_instruction_example.sol#L10

https://github.com/hyperledger/solang/blob/01707781adbe8531b29dfc5a942292e60b8c79a4/integration/solana/system_instruction_example.sol#L26

And here you can find how to wire your client-side code:  

https://github.com/hyperledger/solang/blob/01707781adbe8531b29dfc5a942292e60b8c79a4/integration/solana/system_instruction.spec.ts#L35

https://github.com/hyperledger/solang/blob/01707781adbe8531b29dfc5a942292e60b8c79a4/integration/solana/system_instruction.spec.ts#L109

**Comment by kupermind** [comment]
Thank you for your reply, @LucasSte!

I believe we have tried the suggested approach earlier and had the same issue of `instruction spent from the balance of an account it does not own`, since the setup owner of the account is our program Id, but the transfer ultimately wants the SystemProgram to be invoked with the instruction.

In our approach we wanted to create a PDA  as an escrow account, which is not a regular account, such that nobody would be able to have a private key to access the PDA.

Once again, I appreciate your help and time.

**Comment by LucasSte** [comment]
Hey @kupermind,
I apologize for my terse response. Let me give you a few more details on why I suggested that.

Short answer:
In my opinion, your contract and your client-code in Typescript is correctly structured to created a PDA account and transfer funds out of it. The problem I see is the `create_account_pda` and `transfer_pda`. If you replace these functions respectively by `create_account_with_seed` and `transfer_with_seed` from the SystemInstruction library everything should work as expected.

Long answer:
The Solana runtime identifies the instruction it is going to execute by the first four bytes (a `uint32`) it receives from the call serialized data. In the SystemLibrary, we identify these bytes by the `enum Instruction`. Creating an account or transferring from an account with a seed are not the same instructions as creating an account or transferring from an account without a seed. 

Although in Rust you can directly write `create_account` and `transfer` passing the seeds as an argument, you cannot do so in Solidity. Rust's API automatically chooses the correct instruction based on the presence of the seeds argument. If the seeds are present, it chooses `Instruction.CreateAccountWithSeed` or `Instruction.TransferWithSeed`. If they are not present, it selects `Instruction.CreateAccount` or `Instruction.Transfer`.

In your `create_account_pda` function, you have this line: ` bytes bincode = abi.encode(uint32(Instruction.CreateAccount), lamports, space, owner);` . In other words, you are selecting the `CreateAccount` instruction. It does not matter whether you pass the seeds to the call later or not, they will be ignored because you are not telling the runtime to use them. The function does not fail in your example because it is valid to create an account without seeds and set the `program_id` as its owner. You are not, however, creating a PDA account because the seeds are ignored.

Later, in your `transfer_pda` you have `bytes bincode = abi.encode(uint32(Instruction.Transfer), lamports);`, where you choose the `Transfer` instruction. Again, the runtime ignores the serialized seeds because it has not been told to use them. Passing seeds to the call has no effect. This call fails, as you pointed, because it needs the account owner (the program id) to sign the transaction, whereas you signed it with the PDA account. This is why you get the error `instruction spent from the balance of an account it does not own`. As the account you created is NOT a PDA, it cannot sign its own transaction. 

In order to create a PDA account you must use `create_account_with_seed`. To transfer tokens from that account, you must invoke `transfer_with_seed`.

**Comment by kupermind** [comment]
Hi @LucasSte,

Thank you very much once again for such a detailed response and your help. We are trying that but seems like having issues in some other places now :). Hopefully we get to the bottom of it soon!

Thanks again!

**Comment by LucasSte** [comment]
Hey @kupermind ,
I've cloned your branch and I am testing it too. I'll keep you posted.

**Comment by LucasSte** [comment]
@kupermind,
I misunderstood your problem many times. Sorry for that. I found a fix: https://github.com/valory-xyz/autonolas-registries/pull/102
Is this what you were looking for?
The program ID does not need to own the PDA account. I've followed the tutorial from [here](https://edge.docs.solana.com/developing/programming-model/calling-between-programs#using-program-addresses), where there is no call to `create_account` only to `transfer`.

**Comment by LucasSte** [comment]
> @kupermind,
> I misunderstood your problem many times. Sorry for that. I found a fix: [valory-xyz/autonolas-registries#102](https://github.com/valory-xyz/autonolas-registries/pull/102)
> Is this what you were looking for?
> The program ID does not need to own the PDA account. I've followed the tutorial from [here](https://edge.docs.solana.com/developing/programming-model/calling-between-programs#using-program-addresses), where there is no call to `create_account` only to `transfer`.

Just for completeness, I've found a good reading source for this: https://solana.stackexchange.com/questions/4780/does-a-pda-have-to-be-owned-by-its-signer#:~:text=PDA%20signatures%20are%20verified%20using,one%20that%20was%20passed%20in.

**Comment by LucasSte** [comment]
> We are trying to understand why we were able to fund the account by the means of the system program, but for the transfer back the instruction requires the ownership of a SystemProgram rather than the PDA, since the seed is passed specifically for the PDA.

Basically, the account owner can change any data from the accounts it owns. When you call `transfer`, Solana's SystemProgram changes the balances of the accounts in the transaction. If the SystemProgram does not own an account, you cannot transfer tokens from it.

**Comment by kupermind** [comment]
Hey @LucasSte ,

You are the legend!!! Thank you, thank you, thank you! It finally works!!!

In retrospect we were having the same issue when were trying with just a regular account, meaning when we were doing `create_with_seed()` additionally with the `transfer()`, it was the same permission issue! :) Now we have a much better understanding of where it's coming from.

Once again, thank you for all your advice and invaluable help and engagement. Also, thank you for the links!

This issue can now be closed, and hopefully it will be very useful for other newbies like ourselves. :)

**Comment by LucasSte** [comment]
I'm closing the issue.
Please, @kupermind reach out if you have any more issues.
