### ISSUE TITLE
--target solana: The "msg.sender" is not verified by the payer's signature.

### ISSUE THREAD

**Issue by tunghm0812** [hyperledger/solang#465]
I can change "msg.sender" to any address I want by inserting it into instruction_data. I think we should check "msg.sender" was signed or not. 

```
// instruction_data
const data = Buffer.concat([
            this.contractStorageAccount.publicKey.toBuffer(),
            PublicKey.default.toBuffer(),      // I can change any msg.sender at here.
            Buffer.from('00000000', 'hex'),
            this.encode_seeds(seeds),
            Buffer.from(input.replace('0x', ''), 'hex')
        ]);
```

**Comment by seanyoung** [comment]
You are totally correct. The sender should be checked. However, I'm not sure signing will work for all scenarios.

Say there is an auction contract A, which has its own auxiliary contracts, B and C. 

Now say you want to place a bid. You call A. A can verify that the sender is the correct one, because it is signed. Now A wants to call B or C. It can only do that if there is a signature for A, which you can't provide.

I'm not sure what the solution to this is. One solution would be if CPI could look at the callers instruction, which is not possible yet (I think).

I have not settled on a solution for this. What do you think?

cc: @jackcmay @mvines

**Comment by tunghm0812** [comment]
I think that B or C can verify the sender is A by the "Program Derived Address" account of A.
Example:
`
    // This is signature account of this program.
    // signature_account.is_signed = false
    let seeds = &[b"program_signature", bump_seed];
    let expected_signature_account_key =
            Pubkey::create_program_address(seeds, program_id)?;

    if *signature_account.key != expected_signature_account_key {
        // allocated key does not match the derived address
        return Err(ProgramError::IncorrectProgramId);
    }

    let mut ix = Instruction::new_with_bytes(
        callee_program_id,
        instruction_data,
        vec![AccountMeta::new(*signature_account.key, true)], // set signature_account.is_signed = true (this is msg.sender)
    )

    invoke_signed(
        &ix, 
        &[
            callee_program_id.clone(),
            signature_account.clone(),
        ], 
        &[seeds]) // Only this program_id can call invoke_signed.

    // the callee program can check "msg.sender" by signature_account.is_signed = true in accounts.
`

**Comment by seanyoung** [comment]
If we use that scheme, then anyone who knows the seed of account A can impersonate account A. The seed will be passed into the transaction at various points so this is not a secret.

**Comment by tunghm0812** [comment]
Anyone can know the seed to pass it into the transaction, but only the program_id can call invoke_signed because the signature_account was derived from the program_id.

So A only calls 'invoke_signed' to B or C when everything is correct with its logic.

**Comment by seanyoung** [comment]
I've given it some thought and you are right, this should work. I think this is also needed for value transfers.

It might be possible to simplify seed handling in solang. Should the seed be determined by:
 - Client code and passed into transaction
 - Solidity code
 - Solidity code constant string
 - Simply the name of the solidity contract, so fixed seed
 ?
 
 If w can pick the last option, handling will be much simplified and we'll be saving compute costs.

**Comment by tunghm0812** [comment]
Very good! Congratz. If you need any support or further discussion, you can contact me via email or skype hoangtung.cse@gmail.com.

**Comment by seanyoung** [comment]
I'd rather have a public discussion either here on solana discord.

So the problem I have with client code providing the seed, is that if contract A wants to create a contract, hostile client code has some control of over the seed and thus this is increasing the attack surface.

**Comment by tunghm0812** [comment]
I think we should choose the last option to simplify and save compute costs.

And can you provide an example for the above issue (client code)?

**Comment by seanyoung** [comment]
So the problem with a static seed is that the same contract instantiation might be called multiple types, for example:

```
contract other {
    int public a;
}

contract testing {
        function test(int x) public returns (int) {
            other o;
            do {
                x--;
                o = new other();
            }while(x > 0);

            return o.a();
        }
    }
 ```
 Since the same bpf program_id will be creating an other instance, it will require a unique seed each time. A solution to that would be that the BPF program creates a unique seed every time, but this won't work either.
 - To create a unique seed every time, some state has to be maintained
 - We can only store this state in the account data for the currently running contract
 - An entirely different contract which is not involved in the current transaction might also need to create an `other` contract and does not have access to the state of this contract

So I'm not sure what can be done except for client code providing seed and PDA.

**Comment by seanyoung** [comment]
Yes, you're right. This isssue is no longer relevant
