### ISSUE TITLE
Not able to execute transferFrom function of NFT in substrate 

### ISSUE THREAD

**Issue by Sandeep-Narahari** [hyperledger/solang#768]
I have deployed a NFT smart contract on substrate, except from transferFrom every other function is working fine, i have approved an account but still transferFrom is not working. I am attaching the screenshot of error

![Screenshot from 2022-04-27 16-00-37](https://user-images.githubusercontent.com/46187761/165501351-adbc7b06-ac22-49f1-8ca1-c2754913f1d5.png)

**Comment by Sandeep-Narahari** [comment]
Code for tranferFrom is
`
  function transferFrom(
    address _from,
    address _to,
    uint256 _tokenId
  )
    
    external
    override
  {
    //address tokenOwner = idToOwner[_tokenId];
    address tokenOwner = idToOwner[_tokenId];
    address operator=idToApproval[_tokenId];
    require((msg.sender==tokenOwner || msg.sender==idToApproval[_tokenId]) ,NOT_OWNER_APPROVED_OR_OPERATOR);
    require(ownerToOperators[tokenOwner][operator],"Owner is not approved the operator");
    require(tokenOwner == _from, NOT_OWNER);
    require(_to != address(0), ZERO_ADDRESS);

    _transfer(_to, _tokenId);
  }
`

**Comment by xermicus** [comment]
@Sandeep-Narahari without the full source code of your contracts it's hard to debug this further. However, since there's the `address` type in the function signature, this might be related to #666 and chances are that this is fixed meanwhile. I'm closing this issue, feel free to ping me if you need help.
